parameters:
    mms.idempotent_consumer.messenger_bundle.supported_messages: []
    mms.idempotent_consumer.messenger_bundle.supported_transports: []

services:
    MrAndMrsSmith\IdempotentConsumerSymfonyMessengerBundle\:
        resource: '../'
        autowire: true
        autoconfigure: true
        public: true
        exclude:
            - '../EventSubscriber/*'

    mms.idempotent_consumer.messenger_bundle.event_subscriber:
        class: MrAndMrsSmith\IdempotentConsumerSymfonyMessengerBundle\EventSubscriber\SymfonyMessengerEventSubscriber
        autoconfigure: true
        autowire: true
        arguments:
            $receivers: []
            $supportedTransports: '%mms.idempotent_consumer.messenger_bundle.supported_transports%'
            $supportedMessages: '%mms.idempotent_consumer.messenger_bundle.supported_messages%'
