services:
    MrAndMrsSmith\IdempotentConsumerSymfonyMessengerBundle\:
        resource: '../'
        autowire: true
        autoconfigure: true
        public: true
        exclude:
            - '../EventSubscriber/*'

    mms.idempotent_consumer.messenger_bundle.event_subscriber:
        class: MrAndMrsSmith\IdempotentConsumerSymfonyMessengerBundle\EventSubscriber\SymfonyMessengerEventSubscriber
        autoconfigure: true
        autowire: true
        arguments:
            $receivers: []
            $wantToCheckMessageVoter: '@mms.idempotent_consumer.messenger_bundle.want_to_check_message_voter.transport_and_message'

    mms.idempotent_consumer.messenger_bundle.want_to_check_message_voter.transport:
        class: MrAndMrsSmith\IdempotentConsumerSymfonyMessengerBundle\Voter\WantToCheckMessageByTransportVoter
        autoconfigure: true
        autowire: true

    mms.idempotent_consumer.messenger_bundle.want_to_check_message_voter.message:
        class: MrAndMrsSmith\IdempotentConsumerSymfonyMessengerBundle\Voter\WantToCheckMessageByMessageVoter
        autoconfigure: true
        autowire: true

    mms.idempotent_consumer.messenger_bundle.want_to_check_message_voter.transport_and_message:
        class: MrAndMrsSmith\IdempotentConsumerSymfonyMessengerBundle\Voter\WantToCheckMessageByTransportAndMessageVoter
        autoconfigure: true
        autowire: true
        arguments:
            $transportVoter: '@mms.idempotent_consumer.messenger_bundle.want_to_check_message_voter.transport'
            $messageVoter: '@mms.idempotent_consumer.messenger_bundle.want_to_check_message_voter.message'
